- id: '1649534404435'
  alias: Lock doors at night
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  condition: []
  action:
  - device_id: 614e686fafd1050fc32ad45c20e2abfa
    domain: lock
    entity_id: lock.back_door
    type: lock
  - device_id: d4a330a3abf30e29fe06ea6662a36fe6
    domain: lock
    entity_id: lock.front_door
    type: lock
  mode: single
- id: '1649535064519'
  alias: Turn on deck lights at night
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '-30'
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.deck_lights_are_on
    metadata: {}
  mode: single
- id: '1649786328094'
  alias: Turn off decklights at dawn
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.deck_lights_are_off
    metadata: {}
  mode: single
- id: '1649887519760'
  alias: Backup to github
  description: ''
  trigger:
  - platform: time
    at: 01:02:03
  condition: []
  action:
  - service: shell_command.push_to_github
    data: {}
  mode: single
