
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

shell_command:
  push_to_github: /config/backup-home-assistant_to_git.sh

# ########################################
# ###                GUI               ###
# ########################################

frontend:
  extra_module_url:
    - /hacsfiles/mini-graph-card-bundle.js?v=0.11.0
    - /hacsfiles/button-card/button-card.js
  themes: !include_dir_merge_named themes

# frontend:
#   # extra_module_url:
#   #   - /hacsfiles/lovelace-card-mod/card-mod.js

# lovelace:
#   mode: storage
#   # resources: !include_dir_merge_list lovelace/resources 
#   # dashboards:
#   #   lovelace-main:
#   #     mode: yaml
#   #     filename: "ui-main.yaml"
#   #     title: "1007 main"
#   #     icon: mdi:view-dashboard
#   #     show_in_sidebar: true
#   #     require_admin: false

# lovelace:
#   mode: yaml
#   resources: !include_dir_merge_list lovelace/resources 
#   dashboards:
#     lovelace-dashboard:
#       mode: yaml
#       filename: ui-dashboard.yaml
#       title: Dashboard
#       icon: mdi:monitor-dashboard
#       show_in_sidebar: true
#       require_admin: false

# rainbird:
#   host: 192.168.86.283
#   password: 70albert
#   trigger_time: 360
#   zones:
#     1:
#       friendly_name: Back yard
#       trigger_time:
#         minutes: 90

sensor: !include sensors.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
